FirstProject/urls.py
from django.contrib import admin
from django.urls import path,include
from mainapp.views import Home,About
from django.conf import settings
from django.conf.urls.static import static
from mainapp.views_helper import SearchView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name='home'),
    path('users/',include('accounts.urls',namespace="users")),
    path('post/',include('mainapp.urls',namespace='post')),
    path('about/',About,name='about'),
    path('search/',SearchView,name='search'),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.shortcuts import render
from django.urls import path
from accounts.views import RegisterView,MyLoginView,MyLogoutView,ProfileView,EditProfielView
app_name='accounts'
urlpatterns=[
    path('register/',RegisterView,name='register'),
    path('login/',MyLoginView.as_view(),name='login'),
    path('logout/',MyLogoutView.as_view(),name='logout'),
    path('<str:uname>/',ProfileView,name='profile'),
    path('<str:uname>/edit',EditProfielView,name='editprofile'),
]

mainapp/urls.py
from django.urls import path
from mainapp.views import (
    CreatePost,
    PostDetail,
    DelatePost,
    EditPostView,
    EditPostSave,
    UpvoteView,
    DownvoteView,
    CommentView
)
from mainapp.views_helper import (
    CommentDisplayView,
    CommentEditView,
    CommentDeleteView,
    CommentUpvoteView,
    CommentDownvoteView,
)

app_name='mainapp'
urlpatterns=[
    path('new/',CreatePost,name='newpost'),
    path('<int:id>/',PostDetail,name='post-detail'),
    path('<int:id>/delete/',DelatePost,name='post-delete'),
    path('<int:id>/edit/',EditPostView,name='post-edit'),
    path('<int:id>/edit/save/',EditPostSave,name='post-edit-save'),
    path('<int:id>/upvote/',UpvoteView,name='post-upvote'),
    path('<int:id>/downvote/',DownvoteView,name='post-downvote'),
    path('<int:id>/comment/',CommentView,name='post-comment'),
    path('<int:id>/comment/<int:c_id>/',CommentDisplayView,name='post-comment-view'),
    path('<int:id>/comment/<int:c_id>/save/',CommentEditView,name='post-comment-edit'),
    path('<int:id>/comment/<int:c_id>/delete/',CommentDeleteView,name='post-comment-delete'),
    path('<int:id>/comment/<int:c_id>/downvote/',CommentDownvoteView,name='post-comment-downvote'),
    path('<int:id>/comment/<int:c_id>/upvote/',CommentUpvoteView,name='post-comment-upvote'),
    
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models



class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='default.jpg',upload_to='profile_images')
    country=models.CharField(null=True,blank=True,max_length=20)
    state=models.CharField(null=True,blank=True,max_length=20)
    city=models.CharField(null=True,blank=True,max_length=20)
    about_me=models.CharField(null=True,blank=True,max_length=100)    

    def __str__(self):
        return f'{self.user.username} -profile'

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import Profile


class RegisterForm(UserCreationForm):
    username=forms.CharField(max_length=30,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    email=forms.EmailField(max_length=30,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    password1=forms.CharField(max_length=30,label='Password:',widget=forms.PasswordInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    password2=forms.CharField(max_length=30,label='Password Confirmation:',widget=forms.PasswordInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    class Meta:
        model=User
        fields=['username','email','password1','password2']

class LoginForm(forms.Form):
    username=forms.CharField(max_length=30,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    password=forms.CharField(max_length=30,widget=forms.PasswordInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    class Meta:
        fields=['username','password']


class ProfileUpdateUserForm(forms.ModelForm):
    username=forms.CharField(max_length=30,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    email=forms.EmailField(max_length=30,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    first_name=forms.CharField(max_length=30,required=False,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    last_name=forms.CharField(max_length=30,required=False,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    class Meta:
        model=User
        fields=['username','email','first_name','last_name']

class ProfileUpateMetaForm(forms.ModelForm):
    country=forms.CharField(max_length=30,required=False,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    state=forms.CharField(max_length=30,required=False,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    city=forms.CharField(max_length=30,required=False,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    about_me=forms.CharField(max_length=30,required=False,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    class Meta:
        model=Profile
        fields=['country','state','city','about_me','image']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from mainapp.models import Post
from django.urls import reverse
import math
from accounts.forms import (
    RegisterForm,
    LoginForm,
    ProfileUpdateUserForm,
    ProfileUpateMetaForm,
)
from django.contrib import messages
from django.contrib.auth.views import LoginView,LogoutView
from django.core.paginator import Paginator

#register view 
def RegisterView(request):
    if request.method =='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Account created Successfully! now you can login')
            return redirect('users:login')
    else:
        form=RegisterForm()
    return render(request,'accounts/register.html',{'form':form,'title':'Register'})

class MyLoginView(LoginView):
    template_name='accounts/login.html'
    context_object_name='form'
    class Meta:
        form_class=LoginForm
class MyLogoutView(LogoutView):
    template_name='accounts/logout.html'


def ProfileView(request,uname):
    try:
        requested_user=User.objects.get(username=str(uname))
        posts=Post.objects.filter(author_id=requested_user.id).order_by('-date_posted')
        total=len(posts)
        for post in posts:
            post.title=post.title[0:38]+' -'
            post.content=post.content[0:49]+' ....'
        paginator=Paginator(posts,6)
        temp=request.GET.get('page')
        print('fine1')
        page_number=1
        if temp !=None:
            page_number=temp
        print('fine3')  
        page_obj=paginator.get_page(page_number)
        print('fine4')
        p_r=paginator.page_range
        page_list=[]
        for i in p_r:
            if abs(page_obj.number-i) <=3:
                page_list.append(i)
        print('fine5')
        last=math.ceil(paginator.count/6)
        print('fine2')
        return render(request,'accounts/profile.html',{'title':'Profile','requested_user':requested_user,'page_obj':page_obj,'page_list':page_list,'last':last,'total':total})
    except:
        return render(request,'accounts/pagenotfound.html',{'title':'page not found!'})

@login_required
def EditProfielView(request,uname):
    try:
        request_user=User.objects.filter(username=str(uname)).first()
        user=request.user
        if request_user!=user:
            return render(request,'accounts/pagenotfound.html',{'title':'page not found!'})
        if request.method=='POST':
            form1=ProfileUpdateUserForm(request.POST,request.FILES,instance=user)
            form2=ProfileUpateMetaForm(request.POST,request.FILES,instance=user.profile)
            if form1.is_valid() and form2.is_valid():
                form1.save()
                form2.save()
                return redirect(reverse('users:profile',kwargs={'uname':user.username}))
        else:
            form1=ProfileUpdateUserForm(instance=user)
            form2=ProfileUpateMetaForm(instance=user.profile)
        return render(request,'accounts/editprofile.html',{'form1':form1,'form2':form2})
    except:
        return render(request,'accounts/pagenotfound.html',{'title':'page not found!'})

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href={% static 'accounts/style.css' %} rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'accounts/register.css'%}" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Bhaina+2:wght@500&family=Comic+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
    <script defer src="{% static 'accounts/script.js' %}"></script>
    {% if title %}
    <title>Django Blog - {{title}}</title>
    {% else %}
    <title>Django Blog </title>
    {% endif %}
</head>
<body>
    <div class="navigation-bar">
        <div class="container nav">
            <strong class="nav-element nav-first logo"><a href="{% url 'home' %}">Python Feed</a></strong>
            <p class="nav-element nav-first"><a href="{% url 'home' %}">Home</a></p>
            <p class="nav-element nav-second"><a href="{% url 'about' %}">About</a></p>
            {% if user.is_authenticated %}
            <p class="nav-element nav-first"><a href="{% url 'post:newpost'%}">New Post</a></p>
            <p class="nav-element nav-first"><a href="{% url 'users:profile' user.username %}">Profile</a></p>
            <p class="nav-element nav-first"><a href="{% url 'users:logout' %}">Logout</a></p>
            {% else%}
            <p class="nav-element nav-first"><a href="{% url 'users:login' %}">Login</a></p>
            <p class="nav-element nav-first"><a href="{% url 'users:register' %}">Register</a></p>
            {% endif%}
        </div>
    </div>
    <div class=" main container">
    <div class="main1">
        {% if messages %}
            {% for message in messages%}
                <div class="alert alert-{{message.tags}}">
                    {{message}} 
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock content %}
    </div>
        <div class="main2">
            <div class='blog-main-content'>
                <strong>Our Sidebar</strong>
                <p style='padding-top:8px;'>You can put any information here you'd like.</p>
                <table class="main2-table">
                    <tr><td>Latest Posts</td></tr>
                    <tr><td>Announcements</td></tr>
                    <tr><td>Calendars</td></tr>
                    <tr><td>etc</td></tr>
                </table>
            </div>
            {% block main2 %}
            {% endblock main2 %}
        </div>
    </div>
</body>
</html>

accounts/templates/accounts/editprofile.html
{% extends 'accounts/base.html'%}
{% block content %}
    <div class="blog-main-content">
        <div class="blog-header">
            <h2>Update Profile</h2>
        </div>
        <div class="form-content">
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                {{form1}}
                {{form2}}
                <input type="submit" class="btn-form fw size-30" value="Update Profile">
            </form>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html'%}
{% block content %}
    <div class="blog-main-content">
        <div class="blog-header">
            <h2>Log In</h2>
        </div>
        <div class="form-content">
            <form method='POST'>
                {% csrf_token %}
                {{form}}
                <input type="submit" class="btn-form size-30 fw" value="Log In">
            </form>
        </div>
        <div class="form-ending">
            <small>Need An Account? Register <a href="{% url 'users:register' %}">here</a></small>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/logout.html
{% extends 'accounts/base.html'%}
{% block content %}
    <div class="blog-main-content">
        <div class="blog-header">
            <h2>You Have Been Logged Out Successfully! </h2>
        </div>
            <small>want to login again? click <a href="{% url 'users:login'%}">here</a></small>
    </div>
{% endblock content %}

accounts/templates/accounts/pagenotfound.html
{% extends 'accounts/base.html'%}
{% block content %}
    <div class="blog-main-content">
        <div class="blog-header">
            <h2>Page Not Found Error ! HTTP 404 </h2>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="blog-main-content">
            <div class="profile-image-container">
                <img src="{{requested_user.profile.image.url}}" class="profile-image large-image" alt="{{requested_user.username}}" title="{{requested_user.username}}">
                <div class="blog-content blog-content-data">
                    <h2>{{requested_user.username}}</h2>
                    <p>{{requested_user.email}}</p>
                </div>
            </div>
            <div class="blog-header">
                <h2>User Info</h2>
            </div>
            <table width="100%" class="profile-table">
                <tr> 
                    <td>Username:</td>
                    <td>{{requested_user.username}}</td>
                </tr>
                {% if requested_user.first_name %}
                <tr> 
                    <td>Firstname:</td>
                    <td>{{requested_user.first_name}}</td>
                </tr>
                {%endif %}
                {% if requested_user.last_name %}
                <tr> 
                    <td>Lastname:</td>
                    <td>{{requested_user.last_name}}</td>
                </tr>
                {%endif %}
                <tr>
                    <td>Email:</td>
                    <td>{{requested_user.email}}</td>
                </tr>
                {% if requested_user.profile.country %}
                <tr> 
                    <td>Country:</td>
                    <td>{{requested_user.profile.country}}</td>
                </tr>
                {%endif %}
                {% if requested_user.profile.state %}
                <tr> 
                    <td>State:</td>
                    <td>{{requested_user.profile.state}}</td>
                </tr>
                {%endif %}
                {% if requested_user.profile.city %}
                <tr> 
                    <td>City:</td>
                    <td>{{requested_user.profile.city}}</td>
                </tr>
                {%endif %}
                {% if requested_user.profile.about_me %}
                <tr> 
                    <td>About Me:</td>
                    <td>{{requested_user.profile.about_me}}</td>
                </tr>
                {%endif %}
            </table>
            {% if requested_user == user%}
            <a href="{% url 'users:editprofile' user.username %}">
                <input type="button" class="btn-form size-30 fw" value="Edit Profile">
            </a>
            {%endif %}
    </div>
            {% if total > 0%}
                <div class="blog-main-content">
                    <h2>{{ requested_user.username}}'s all posts | total: {{total}}</h2>
                </div>
                {% for post in page_obj%}
                <div class="blog-main-content">
                        <div class="profile-image-container">
                            <img src="{{post.author.profile.image.url}}" class="profile-image small-image"  alt="{{post.author.username}}" title="{{post.author.username}}">
                            <div class="blog-content">
                                <div class="blog-header-post">
                                    <div>
                                    <span class="author-name ">{{ post.author }}</span> &nbsp;
                                    <span class="blog-date">{{ post.date_posted | date:'F d Y' }}</span> &nbsp; | &nbsp;
                                    <span class='blog-date'>{{post.time_ago}}</span> 
                                    </div>
                                    <div>
                                    <span class='likes'><span class='like-btn'>likes</span><span class='like-data'>{{ post.upvote_count }}</span></span>
                                    <span class='likes'><span class='like-btn'>dislikes</span><span class='like-data'>{{ post.downvote_count }}</span></span>
                                    <span class='likes'><span class='like-btn'>comments</span><span class='like-data'>{{ post.comment_count }}</span></span>  
                                </div>
                                </div>
                                <div>
                                        <a href={% url 'post:post-detail' post.id%} class="normal-link"><h3>{{ post.title}}</h3></a>
                                        <p style='margin-top:4px'>{{ post.content }}<a href="{% url 'post:post-detail' post.id%}" class="normal-link">read more</a></p>
                                </div>
                            </div>
                        </div>
                </div>
                {% endfor%}
                <div class='paginator-container'>
                    {% if page_obj.has_previous %}
                            <a href='?page=1' class='normal-link btn paginate-inactive'>First</a>
                            <a href='?page={{ page_obj.previous_page_number }}' class='normal-link btn paginate-inactive'>Previous</a>
                    {% endif %}
                    {% for num in page_list %}
                            {% if num is page_obj.number %}
                                    <a href='?page={{num}}' class='normal-link btn paginate-active'>{{num}}</a>
                            {% else %}
                                    <a href="?page={{num}}" class='normal-link btn paginate-inactive'>{{num}}</a>
                            {% endif %}      
                    {% endfor %}
                    {% if page_obj.has_next %}
                            <a href='?page={{ page_obj.next_page_number }}' class='normal-link btn paginate-inactive'>next</a>
                            <a href='?page={{last}}' class='normal-link btn paginate-inactive'>Last</a>
                    {% endif %}
                </div>
            {%  else %}
            <div class="blog-main-content">
                <h2>{{ requested_user.username}} haven't wrote any post yet!</h2>
            </div>
            {% endif %}
{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html'%}
{% block content %}
    <div class="blog-main-content">
        <div class="blog-header">
            <h2>Join Today!</h2>
        </div>
        <div class="form-content">
            <form method='POST'>
                {% csrf_token %}
                {{form}}
                <input type="submit" class="btn-form fw size-30" value="Sign Up">
            </form>
        </div>
        <div class="form-ending">
            <small>Already Have An Account? Login <a href="{% url 'users:login' %}">here</a></small>
        </div>
    </div>
{% endblock content %}