FirstProject/urls.py
from django.contrib import admin
from django.urls import path,include
from mainapp.views import Home,About
from django.conf import settings
from django.conf.urls.static import static
from mainapp.views_helper import SearchView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name='home'),
    path('users/',include('accounts.urls',namespace="users")),
    path('post/',include('mainapp.urls',namespace='post')),
    path('about/',About,name='about'),
    path('search/',SearchView,name='search'),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.shortcuts import render
from django.urls import path
from accounts.views import RegisterView,MyLoginView,MyLogoutView,ProfileView,EditProfielView
app_name='accounts'
urlpatterns=[
    path('register/',RegisterView,name='register'),
    path('login/',MyLoginView.as_view(),name='login'),
    path('logout/',MyLogoutView.as_view(),name='logout'),
    path('<str:uname>/',ProfileView,name='profile'),
    path('<str:uname>/edit',EditProfielView,name='editprofile'),
]

mainapp/urls.py
from django.urls import path
from mainapp.views import (
    CreatePost,
    PostDetail,
    DelatePost,
    EditPostView,
    EditPostSave,
    UpvoteView,
    DownvoteView,
    CommentView
)
from mainapp.views_helper import (
    CommentDisplayView,
    CommentEditView,
    CommentDeleteView,
    CommentUpvoteView,
    CommentDownvoteView,
)

app_name='mainapp'
urlpatterns=[
    path('new/',CreatePost,name='newpost'),
    path('<int:id>/',PostDetail,name='post-detail'),
    path('<int:id>/delete/',DelatePost,name='post-delete'),
    path('<int:id>/edit/',EditPostView,name='post-edit'),
    path('<int:id>/edit/save/',EditPostSave,name='post-edit-save'),
    path('<int:id>/upvote/',UpvoteView,name='post-upvote'),
    path('<int:id>/downvote/',DownvoteView,name='post-downvote'),
    path('<int:id>/comment/',CommentView,name='post-comment'),
    path('<int:id>/comment/<int:c_id>/',CommentDisplayView,name='post-comment-view'),
    path('<int:id>/comment/<int:c_id>/save/',CommentEditView,name='post-comment-edit'),
    path('<int:id>/comment/<int:c_id>/delete/',CommentDeleteView,name='post-comment-delete'),
    path('<int:id>/comment/<int:c_id>/downvote/',CommentDownvoteView,name='post-comment-downvote'),
    path('<int:id>/comment/<int:c_id>/upvote/',CommentUpvoteView,name='post-comment-upvote'),
    
]

mainapp/models.py

from django.db import models
from django.utils import timezone  
from django.contrib.auth.models import User
from django.urls import reverse

class PostTag(models.Model):
    name=models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Post(models.Model):
    title=models.CharField(max_length=50)
    content=models.TextField()
    date_posted=models.DateTimeField(default=timezone.now)
    post_thumnail=models.ImageField(blank=True,null=True,upload_to='post_thumbnails')
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='author')
    upvoted_users=models.ManyToManyField(User,blank=True,related_name='upvote')
    downvoted_users=models.ManyToManyField(User,blank=True,related_name='downvote')
    upvote_count=models.IntegerField(default=0)
    downvote_count=models.IntegerField(default=0)
    comments=models.ManyToManyField(User,through='Comment',through_fields=('post','user'),blank=True,related_name='comments')
    comment_count=models.IntegerField(default=0)
    points=models.IntegerField(default=0)
    tags=models.ManyToManyField(PostTag,blank=True,related_name='posts')
    def __str__(self):
        return f'post - {self.title}'
    def get_absolute_url(self,*args,**kwargs):
        return reverse('post:post-detail',kwargs={'id':self.id})
    def time_ago(self):
        tp=self.date_posted
        tn=timezone.now()
        return self.time_calc(tp,tn)
    #finding time since posted
    def time_calc(self,tp,tn):
        if tn.year-tp.year >0:
            return str(tn.year-tp.year) + ' years ago'
        if tn.month-tp.month >0:
            return str(tn.month-tp.month) +' months ago'
        if tn.day-tp.day >0:
            return str(tn.day-tp.day) + ' days ago'
        if tn.hour-tp.hour >0:
            return str(tn.hour-tp.hour) +' hours ago'
        if tn.minute-tp.minute >0:
            return str(tn.minute-tp.minute) + ' minutes ago'
        if tn.second-tp.second >0:
            return str(tn.second-tp.second) + ' seconds ago'
        else:
            return 'just now'
    def set_upvote_count(self):
        self.upvote_count=self.upvoted_users.count()
    def set_downvote_count(self):
        self.downvote_count=self.downvoted_users.count()
    def set_comment_count(self):
        self.comment_count=Comment.objects.filter(post=self).count()
    def set_points(self):
        self.points=self.upvote_count-self.downvote_count

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comment_post')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='comment_user')
    content=models.TextField()
    comment_upvoted_users=models.ManyToManyField(User,related_name='comment_upvoted_users')
    comment_downvoted_users=models.ManyToManyField(User,related_name='comment_downvoted_users')
    comment_upvote_count=models.IntegerField(default=0)
    comment_downvote_count=models.IntegerField(default=0)
    date_commented=models.DateTimeField(default=timezone.now)

    def set_comment_upvote_count(self):
        self.comment_upvote_count=self.comment_upvoted_users.count()
    def set_comment_downvote_count(self):
        self.comment_downvote_count=self.comment_downvoted_users.count()

mainapp/mainapp/forms.py
from django import forms
from .models import Post,Comment

class CreatePostForm(forms.ModelForm):
    title=forms.CharField(max_length=100,widget=forms.TextInput(
        attrs={
            'class':'fw size-30',
        }
    ))
    content=forms.CharField(max_length=5000,widget=forms.Textarea(
        attrs={
            'class':'fw size-400',
            'placeholder':'write here'
        }
    ))
    post_thumnail=forms.ImageField(label='thumbnail (optional):',required=False)
    class Meta:
        model=Post
        fields=['title','post_thumnail','content']
        
class CommentForm(forms.ModelForm):
    content=forms.CharField(label='',max_length=5000,widget=forms.Textarea(
        attrs={
            'class':'fw size-400',
            'placeholder':'comment here'
        }
    ))
    class Meta:
        model=Comment
        fields=['content',]

mainapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from mainapp.forms import CreatePostForm,CommentForm
from mainapp.models import Post,Comment,PostTag
from django.contrib.auth.models import User,AnonymousUser
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import Count,Sum
import json
import math  

def home_helper(queryset,tag_filter_list):
    if tag_filter_list is None:
        return queryset
    else:
        return queryset.filter(tags__name__in=tag_filter_list).distinct()
def Home(request):
    f_type=request.GET.get('filter')
    json_encoded_string=request.GET.get('tag')
    tag_filter_list=None
    if not json_encoded_string is None:
        json_obj=eval(json_encoded_string)
        tag_filter_list=json_obj['tags']
    if f_type==None:
        f_type=0
    f_type=int(f_type)
    queryset=Post.objects.all()
    queryset=home_helper(queryset,tag_filter_list)
    if f_type ==2:
        posts=queryset.order_by('-points','-author_id')
    else:
        posts=queryset.order_by('-date_posted')
    for post in posts:
        post.title=post.title[0:38]+' -'
        post.content=post.content[0:49]+' ....'
    paginator=Paginator(posts,6)
    temp=request.GET.get('page')
    page_number=1
    if temp !=None:
        page_number=temp  
    page_obj=paginator.get_page(page_number)
    page_range=paginator.page_range
    total=len(posts)
    page_list=[]
    for i in page_range:
        if abs(page_obj.number-i) <=3:
            page_list.append(i)
    last=math.ceil(paginator.count/6)
    tag_query_set=PostTag.objects.values('name').annotate(post_count=Count('posts'))
    user_likes=0
    user_posts=0
    if request.user.is_authenticated:
        user=request.user
        user_likes=Post.objects.filter(author__username=user.username).aggregate(like_count=Sum('upvote_count')).get('like_count')
        user_posts=Post.objects.filter(author__username=user.username).count()
    return render(request,'mainapp/home.html',{'page_obj':page_obj,'tag_filter_list':tag_filter_list,
    'page_list':page_list,'last':last,'total':total,'tag_query_set':tag_query_set,
    'f_type':f_type,'user_likes':user_likes,'user_posts':user_posts})

def About(request):
    return render(request,'mainapp/about.html',{'title':'About Us'})
@login_required
def CreatePost(request):
    tag_list=PostTag.objects.all()
    if request.method=='POST':
        form=CreatePostForm(request.POST,request.FILES)
        if form.is_valid():
            form.instance.author=request.user
            tag_query_set=PostTag.objects.filter(name__in=request.POST.getlist('tags'))
            form.instance.save()
            if tag_query_set.count()==0:
                form.instance.tags.add(PostTag.objects.get('General'))
            else:
                for tag in tag_query_set:
                    form.instance.tags.add(tag)
            return redirect(form.instance.get_absolute_url())
    else:
        form=CreatePostForm()
    return render(request,'mainapp/createpost.html',{'form':form,'title':'Create Post','tag_list':tag_list})
    
def PostDetail(request,id):
    try:
        page=1
        f_type=1
        if request.GET.get('page') !=None:
            page=request.GET.get('page')
        if request.GET.get('filter')!=None:
            f_type=request.GET.get('filter')
        post=Post.objects.get(pk=id)
        f_type=int(f_type)
        if f_type==2:
            comment_list=Comment.objects.filter(post=post).order_by('-comment_upvote_count','-date_commented')
        else:
            comment_list=Comment.objects.filter(post=post).order_by('-date_commented')
        paginator=Paginator(comment_list,5)
        page_obj=paginator.get_page(page)
        page_range=paginator.page_range
        total=len(comment_list)
        page_list=[]
        for i in page_range:
            if abs(page_obj.number-i) <=3:
                page_list.append(i)
        last=math.ceil(paginator.count/5)
        upvoted_set={-1,}
        downvoted_set={-1,}
        if request.user.is_authenticated:
            upvote=False
            downvote=False
            user=request.user 
            if post.upvoted_users.filter(id=user.id).exists():
                upvote=True
            elif post.downvoted_users.filter(id=user.id).exists():
                downvote=True
            form=CommentForm()
            for comment in comment_list:
                if comment.comment_upvoted_users.filter(id=user.id).exists():
                    upvoted_set.add(comment.id)
                if comment.comment_downvoted_users.filter(id=user.id).exists():
                    downvoted_set.add(comment.id)
            return render(request,'mainapp/postdetail.html',
            {'post':post,
            'upvote':upvote,
            'downvote':downvote,
            'comment_write':True,
            'form':form,
            'page_obj':page_obj,
            'page_list':page_list,
            'last':last,
            'total':total,
            'upvoted_set':upvoted_set,
            'downvoted_set':downvoted_set,})
        else:
            return render(request,'mainapp/postdetail.html',
            {'post':post,
            'comment_write':False,
            'page_obj':page_obj,
            'page_list':page_list,
            'upvoted_set':upvoted_set,
            'downvoted_set':downvoted_set,})
    except:
        return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
@login_required
def DelatePost(request,id):
    if request.method=='POST':
        user=request.user
        try:
            post=Post.objects.get(id=id)
            if post.author==user:
                post.delete()
                return redirect('home')
            else:
                return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
        except:
            return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
    else:
        return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})

@login_required
def EditPostView(request,id):
    if request.method=='POST':
        try:
            post=Post.objects.get(id=id)
            user=request.user
            if user==post.author:
                form=CreatePostForm(instance=post)
                return render(request,'mainapp/editpost.html',{'form':form})
            else:
                return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
        except:
            return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
    else:
        return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
 
@login_required
def EditPostSave(request,id):
    if request.method=='POST':
        try:
            post=Post.objects.get(id=id)
            user=request.user
            if user==post.author:
                form=CreatePostForm(request.POST,request.FILES,instance=post)
                if form.is_valid():
                    form.save()
                    return redirect(reverse('post:post-detail',kwargs={'id':post.id}))
                else:
                    return render(request,'mainapp/editpost.html',{'form':form})
            else:
                return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
        except:
            return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
    else:
        return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
@login_required
def UpvoteView(request,id):
    if request.method=='POST':
        try:
            post=Post.objects.get(id=id)
            user=request.user
            if post.downvoted_users.filter(id=user.id).exists():
                post.downvoted_users.remove(user)
                post.upvoted_users.add(user)
            elif post.upvoted_users.filter(id=user.id).exists():
                post.upvoted_users.remove(user)
            else:
                post.upvoted_users.add(user)
            post.set_upvote_count()
            post.set_downvote_count()
            post.set_points()
            post.save()
            return redirect(reverse('post:post-detail',kwargs={'id':post.id,}))
        except:
            return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
    else:
        return redirect(reverse('post:post-detail',kwargs={'id':id}))
@login_required
def DownvoteView(request,id):
    if request.method=='POST':
        try:
            post=Post.objects.get(id=id)
            user=request.user
            if post.upvoted_users.filter(id=user.id).exists():
                post.upvoted_users.remove(user)
                post.downvoted_users.add(user)
            elif post.downvoted_users.filter(id=user.id).exists():
                post.downvoted_users.remove(user)
            else:
                post.downvoted_users.add(user)
            post.set_upvote_count()
            post.set_downvote_count()
            post.set_points()
            post.save()
            return redirect(reverse('post:post-detail',kwargs={'id':post.id,}))
        except:
            return render(request,'accounts/pagenotfound.html',{'title':'HTTP 404 ERROR'})
    else:
        return redirect(reverse('post:post-detail',kwargs={'id':id}))

@login_required
def CommentView(request,id):
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            content=form.cleaned_data.get('content') 
            post=Post.objects.filter(id=id).first()
            user=request.user
            Comment.objects.create(post=post,user=user,content=content)
            post.set_comment_count()

mainapp/templates/mainapp/about.html
{% extends 'accounts/base.html'%}
{% block content %}
    <div class="blog-main-content">
        <div class="blog-header">
            <h2>About Us</h2>
        </div>
        <div class="post-content">
            <p>we the professional programmers ,we never backdown
            from any pain, we work hard until we get enough!</p><br>
            <p>In this site we encourage you to join and write 
            some useful posts that might help others and please 
            support us </p><br>
            by <br>
            Team bobby
        </div>
    </div>
{% endblock content %}

mainapp/templates/mainapp/postdetail.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="blog-main-content">
        <div class="blog-header">
            <div class="profile-image-container">
                <img src="{{post.author.profile.image.url}}" class="profile-image small-image"  alt="{{post.author.username}}" title="{{post.author.username}}">
                <div class="blog-content">
                    <div class="blog-header-post">
                        <div>posted by
                        <span class="author-name"><a href={% url 'users:profile' post.author.username %} class='normal-link'>{{ post.author }}</a></span> &nbsp;
                        <span class="blog-date">{{ post.date_posted | date:'F d Y' }}</span> &nbsp; | &nbsp;
                        <span class='blog-date'>{{post.time_ago}}</span> 
                        </div>
                        <div>
                        <span class='likes'><span class='like-btn'>likes</span><span class='like-data'>{{ post.upvote_count }}</span></span>
                        <span class='likes'><span class='like-btn'>dislikes</span><span class='like-data'>{{ post.downvote_count }}</span></span>
                        </div>
                    </div>

                        <div class='btn-container'>
                            {% if user and user == post.author %}
                            <div>
                               <form method='POST' action='delete/' style="display: inline;"> {% csrf_token%}<input type="submit" value="Delete" class="btn btn-danger"></form>
                               <form method='POST' action='edit/' style="display: inline;"> {% csrf_token%}<input type="submit" value="Edit" class="btn btn-blue"></form>
                            </div>
                            {% endif %}
                            <div>
                                {% if upvote is True %}
                               <form method='POST' action='upvote/' style="display: inline;"> {% csrf_token%}<input type="submit" value="Liked" class="btn btn-liked"></form>
                                {% else %}
                               <form method='POST' action='upvote/' style="display: inline;"> {% csrf_token%}<input type="submit" value="Like" class="btn btn-white"></form>
                                {% endif %}
                                {% if downvote is True %}
                                <form method='POST' action='downvote/' style="display: inline;"> {% csrf_token%}<input type="submit" value="Disliked" class="btn btn-liked"></form>
                                 {% else %}
                                <form method='POST' action='downvote/' style="display: inline;"> {% csrf_token%}<input type="submit" value="Dislike" class="btn btn-white"></form>
                                 {% endif %}
                            </div>
                        </div>
                </div>
             </div>
        </div><br>
        <div class="blog-content">
            
            <h2>{{post.title}}</h2>
            {% if post.post_thumnail %}
            <br>
            <img src="{{post.post_thumnail.url}}" class='post-image' title='{{post.title}}' alt="thumbnail">
            <br>
            {% endif %}
            <p class="post-content">{{post.content| urlizetrunc:35 | linebreaks}}</p>
        </div>
        <br>
        <div class="blog-header">
            <h3>Comments ({{post.comment_count}})</h3>
        </div><br>
        {% if comment_write is True %}
        <div class="blog-content">
            <form  action="comment/" method="post">
                {% csrf_token %}
                {{form}}
                <input type="submit" value="comment" class='btn-form fw size-30'>
            </form>
        </div>
        {% else%}
        <p>want to comment? login <a href='{% url 'users:login' %}?next={{post.get_absolute_url}}'>Here</a> </p>
        {% endif %}
        <br>
        <div class="blog-content"><br>
            {% for comment in page_obj %}
            <br>
            <div class="profile-image-container">
                <img src="{{comment.user.profile.image.url}}" class="profile-image very-small-image"  alt="{{comment.user.username}}" title="{{comment.user.username}}">
                <div class="blog-content">
                    <div class="blog-header-post">
                        <div>commented by
                        <span class="author-name"><a href={% url 'users:profile' comment.user.username %} class='normal-link'>{{ comment.user.username }}</a></span> &nbsp;
                        <span class='blog-date'>{{comment.date_commented | timesince }} ago</span> 
                        </div>
                        <div>
                        <span class='likes'><span class='like-btn'>likes</span><span class='like-data'>{{ comment.comment_upvote_count }}</span></span>
                        <span class='likes'><span class='like-btn'>dislikes</span><span class='like-data'>{{ comment.comment_downvote_count }}</span></span>
                        </div>
                    </div>
                        <div class="blog-cotent">
                            <p>{{comment.content}}</p>
                        </div>
                        <br>
                        <div class='btn-container'>
                            {% if user and user == comment.user %}
                            <div>
                               <form method='POST' action='{% url 'post:post-comment-delete' post.id comment.id %}' style="display: inline;"> {% csrf_token%}<input type="submit" value="Delete" class="btn-danger btn-small"></form>
                               <form method='POST' action='{% url 'post:post-comment-view' post.id comment.id %}' style="display: inline;"> {% csrf_token%}<input type="submit" value="Edit" class="btn-blue btn-small"></form>
                            </div>
                            {% endif %}
                            <div>
                                {% if comment.id in upvoted_set %}
                               <form method='POST' action='{% url 'post:post-comment-upvote' post.id comment.id %}' style="display: inline;"> {% csrf_token%}<input type="submit" value="Liked" class="btn-small btn-liked"></form>
                                {% else %}
                               <form method='POST' action='{% url 'post:post-comment-upvote' post.id comment.id %}' style="display: inline;"> {% csrf_token%}<input type="submit" value="Like" class="btn-small btn-white"></form>
                                {% endif %}
                                {% if comment.id in downvoted_set %}
                                <form method='POST' action='{% url 'post:post-comment-downvote' post.id comment.id %}' style="display: inline;"> {% csrf_token%}<input type="submit" value="Disliked" class="btn-small btn-liked"></form>
                                 {% else %}
                                <form method='POST' action='{% url 'post:post-comment-downvote' post.id comment.id %}' style="display: inline;"> {% csrf_token%}<input type="submit" value="Dislike" class="btn-small btn-white"></form>
                                 {% endif %}
                            </div>
                        </div>
                </div>
             </div>
                <hr>
            {% endfor %}
        </div>
    </div>
    {% if post.comment_count > 0 %}
    <div class='paginator-container'>
        {% if page_obj.has_previous %}
                <span onclick="append_attrib('page',1)" class='normal-link btn paginate-inactive'>First</span>
                <span onclick="append_attrib('page',{{page_obj.previous_page_number}})" class='normal-link btn paginate-inactive'>Previous</span>
        {% endif %}
        {% for num in page_list %}
                {% if num is page_obj.number %}
                        <span onclick="append_attrib('page',{{num}})" class='normal-link btn paginate-active'>{{num}}</span>
                {% else %}
                        <span onclick="append_attrib('page',{{num}})" class='normal-link btn paginate-inactive'>{{num}}</span>
                {% endif %}      
        {% endfor %}
        {% if page_obj.has_next %}
                <span onclick="append_attrib('page',{{page_obj.next_page_number}})" class='normal-link btn paginate-inactive'>next</span>
                <span onclick="append_attrib('page',{{last}})" class='normal-link btn paginate-inactive'>Last</span>
        {% endif %}
    </div>
    {% endif %}
{% endblock content%}
{% block main2 %}
        <div class="blog-main-content">
                <div class="blog-header">
                        <h3>Filter Comments By</h3>
                </div>
                <div class="blog-content">
                        <div>
                             <input type="radio" name="filter" onclick="append_attrib('filter',1)" class='radio-btn' id='rd1'><label for='rd1'>Recency</label>
                        </div>
                        <div style='margin-top:5px;'>
                          <input type="radio" name="filter" onclick="append_attrib('filter',2)" class="radio-btn" id='rd2'><label for='rd2'>Most likes</label>
                        </div>
                </div>
        </div>
{% endblock main2 %}

mainapp/templates/mainapp/search.html
{% extends 'accounts/base.html' %}

{% block content%}
    <div class="blog-main-content">
        <div class="blog-header">
            <h3>search results : Authors ({{user_count}})</h3>
        </div>
        <br>
        {% if user_total == 0%}
        <h5>No User Found!</h5>
        {%else%}
        {% for author in user_page_obj %}
        <div class="user-search-result">
            <img src="{{author.image.url}}" class='profile-image very-small-image' alt="{{author.user.username}}" title="{{author.user.username}}">
            <a href="{% url 'users:profile' author.user.username%}">{{author.user.username}}</a>
        </div>
        {% endfor %}
        {%endif %}
        <div style='margin-top:5px; display:flex; justify-content:space-between;'>
        {%  if not user_total ==  0 %}
        {% if user_page_obj.has_previous %}
        <span onclick="append_attrib('user-search',{{user_page_obj.previous_page_number}})" class='normal-link'>previous page</span>
       {%else%}
       <span></span>
        {% endif %}
        {% if user_page_obj.has_next %}
        <span onclick="append_attrib('user-search',{{user_page_obj.next_page_number}})" class='normal-link'>next page</span>
        {%else%}
        <span></span>
        {% endif %}
        {%endif %}
        </div>
    </div>
        <div class="blog-main-content">
            <div class="blog-header">
                <h3>search results : Posts ({{post_count}})</h3>
            </div>
            <br>
            {% if total == 0 %}
            <h5>No Post Found!</h5>
            {% else %}
            {% for post in page_obj %}
            <div class="profile-image-container" style='border-bottom: 1px solid lightgrey;margin-top:5px; padding-bottom:5px;'>
            <img src="{{post.author.profile.image.url}}" class="profile-image very-small-image"  alt="{{post.author.username}}" title="{{post.author.username}}">
            <div class="blog-content">
                    <div  style="display:flex; justify-content:space-between; border-bottom:1px solid lightgrey;margin-bottom:2px; padding-bottom:2px;">
                            <div>
                            <span class="author-name"><a href={% url 'users:profile' post.author.username %} class='normal-link'><small>{{ post.author }}</small></a></span> &nbsp;
                            <span class="blog-date">{{ post.date_posted | date:'F d Y' }}</span> &nbsp; | &nbsp;
                            <span class='blog-date'>{{post.time_ago}}</span>
                            </div>
                            <div>
                            <span class='likes'><span class='like-btn'>likes</span><span class='like-data'>{{ post.upvote_count }}</span></span>
                            <span class='likes'><span class='like-btn'>dislikes</span><span class='like-data'>{{ post.downvote_count }}</span></span>
                            <span class='likes'><span class='like-btn'>comments</span><span class='like-data'>{{ post.comment_count }}</span></span>
                        </div>
                    </div>
                    <div>
                            <a href={% url 'post:post-detail' post.id%} class="normal-link"><h5>{{ post.title}}</h5></a>
                    </div>
            </div>
            </div>
            {% endfor %}
            {%endif %}
    </div>
    {% if not total is 0 %}
    <div class='paginator-container'>
        {% if page_obj.has_previous %}
                <span onclick="append_attrib('page',1)" class='normal-link btn paginate-inactive'>First</span>
                <span onclick="append_attrib('page',{{page_obj.previous_page_number}})" class='normal-link btn paginate-inactive'>Previous</span>
        {% endif %}
        {% for num in page_list %}
                {% if num is page_obj.number %}
                        <span onclick="append_attrib('page',{{num}})" class='normal-link btn paginate-active'>{{num}}</span>
                {% else %}
                        <span onclick="append_attrib('page',{{num}})" class='normal-link btn paginate-inactive'>{{num}}</span>
                {% endif %}      
        {% endfor %}
        {% if page_obj.has_next %}
                <span onclick="append_attrib('page',{{page_obj.next_page_number}})" class='normal-link btn paginate-inactive'>next</span>
                <span onclick="append_attrib('page',{{last}})" class='normal-link btn paginate-inactive'>Last</span>
        {% endif %}
    </div>
    {%endif %}
{% endblock content %}